services:
  elasticsearch:
    image: elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ~/docker/volumes/elastic-dev:/usr/share/elasticsearch/data
